### PR TITLE
Changed notation of the acceptable into (A)

### PR DESCRIPTION
**Pull request by enpuyou**
This merge will change the original notation of Acceptable (C) into (A) in order to pass the proselint. Thank you! @Michionlion @sutterj @toccinAC

### CODE REVIEW

**Review by Michionlion — CHANGES_REQUESTED** [review]
The lines in the Travis CI configuration related to moving the `.proselintrc`, as well as the proselint configuration itself, should be removed.

**Comment by enpuyou** [comment]
Removed the Travis CI configuration that regarded to the issue

**Review by Michionlion — APPROVED** [review]
Looks good!

**Review by gkapfham — APPROVED** [review]
I think that this proposed change is fine. Thanks!

**Review by shafferz — APPROVED** [review]
I just noticed this myself when working on the next lab assignment, and was planning on proposing a fix. You beat me to it! I think this change is both acceptable and will help all of us moving forward on the future lab assignments.

**Review by aubreypc — APPROVED** [review]
Good fix, thanks for the PR 🔥

**Pull request merged**
